//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: rl.proto
// Note: requires additional types generated from: common.proto
namespace MSG
{
  [global::ProtoBuf.ProtoContract]
  public partial class ThinkReq
  {
    public ThinkReq() {}
    
    private uint _botNo;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint botNo
    {
      get { return _botNo; }
      set { _botNo = value; }
    }
    private readonly global::System.Collections.Generic.List<float> _newStates = new global::System.Collections.Generic.List<float>();
    [global::ProtoBuf.ProtoMember(2, DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public global::System.Collections.Generic.List<float> newStates
    {
      get { return _newStates; }
    }
  
    private float _reward;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float reward
    {
      get { return _reward; }
      set { _reward = value; }
    }
    private bool _done;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool done
    {
      get { return _done; }
      set { _done = value; }
    }
  }
  
  [global::ProtoBuf.ProtoContract]
  public partial class ThinAns
  {
    public ThinAns() {}
    
    private MSG.ErrorCode _error;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public MSG.ErrorCode error
    {
      get { return _error; }
      set { _error = value; }
    }
    private uint _botNo;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint botNo
    {
      get { return _botNo; }
      set { _botNo = value; }
    }
    private readonly global::System.Collections.Generic.List<float> _actions = new global::System.Collections.Generic.List<float>();
    [global::ProtoBuf.ProtoMember(3, DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public global::System.Collections.Generic.List<float> actions
    {
      get { return _actions; }
    }
  
  }
  
}