//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: chat.proto
// Note: requires additional types generated from: common.proto
namespace MSG
{
  [global::ProtoBuf.ProtoContract]
  public partial class ChatReq
  {
    public ChatReq() {}
    
    private string _msg;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string msg
    {
      get { return _msg; }
      set { _msg = value; }
    }
    private MSG.ChatType _type;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public MSG.ChatType type
    {
      get { return _type; }
      set { _type = value; }
    }
  }
  
  [global::ProtoBuf.ProtoContract]
  public partial class ChatAns
  {
    public ChatAns() {}
    
    private MSG.ErrorCode _err;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public MSG.ErrorCode err
    {
      get { return _err; }
      set { _err = value; }
    }
  }
  
  [global::ProtoBuf.ProtoContract]
  public partial class ChatNot
  {
    public ChatNot() {}
    
    private MSG.ChatData_ _chats;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, DataFormat = global::ProtoBuf.DataFormat.Default)]
    public MSG.ChatData_ chats
    {
      get { return _chats; }
      set { _chats = value; }
    }
    private MSG.ChatType _type;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public MSG.ChatType type
    {
      get { return _type; }
      set { _type = value; }
    }
  }
  
  [global::ProtoBuf.ProtoContract]
  public partial class CreateChatRoomReq
  {
    public CreateChatRoomReq() {}
    
    private string _name;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private string _greeting;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string greeting
    {
      get { return _greeting; }
      set { _greeting = value; }
    }
  }
  
  [global::ProtoBuf.ProtoContract]
  public partial class CreateChatRoomAns
  {
    public CreateChatRoomAns() {}
    
    private MSG.ErrorCode _err;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public MSG.ErrorCode err
    {
      get { return _err; }
      set { _err = value; }
    }

    private ulong _rid = default(ulong);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong rid
    {
      get { return _rid; }
      set { _rid = value; }
    }

    private string _rkey = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string rkey
    {
      get { return _rkey; }
      set { _rkey = value; }
    }
  }
  
  [global::ProtoBuf.ProtoContract]
  public partial class InviteChatRoomReq
  {
    public InviteChatRoomReq() {}
    
    private ulong _rid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong rid
    {
      get { return _rid; }
      set { _rid = value; }
    }
    private string _rkey;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string rkey
    {
      get { return _rkey; }
      set { _rkey = value; }
    }
    private ulong _targetUid;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong targetUid
    {
      get { return _targetUid; }
      set { _targetUid = value; }
    }
    private string _targetName;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string targetName
    {
      get { return _targetName; }
      set { _targetName = value; }
    }
  }
  
  [global::ProtoBuf.ProtoContract]
  public partial class InviteChatRoomAns
  {
    public InviteChatRoomAns() {}
    
    private MSG.ErrorCode _err;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public MSG.ErrorCode err
    {
      get { return _err; }
      set { _err = value; }
    }
  }
  
  [global::ProtoBuf.ProtoContract]
  public partial class InviteChatRoomNot
  {
    public InviteChatRoomNot() {}
    
    private ulong _rid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong rid
    {
      get { return _rid; }
      set { _rid = value; }
    }
    private string _rkey;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string rkey
    {
      get { return _rkey; }
      set { _rkey = value; }
    }
    private ulong _ownerUid;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong ownerUid
    {
      get { return _ownerUid; }
      set { _ownerUid = value; }
    }
    private string _ownerName;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string ownerName
    {
      get { return _ownerName; }
      set { _ownerName = value; }
    }
  }
  
  [global::ProtoBuf.ProtoContract]
  public partial class EnterChatRoomReq
  {
    public EnterChatRoomReq() {}
    
    private ulong _rid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong rid
    {
      get { return _rid; }
      set { _rid = value; }
    }
    private string _rkey;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string rkey
    {
      get { return _rkey; }
      set { _rkey = value; }
    }
  }
  
  [global::ProtoBuf.ProtoContract]
  public partial class EnterChatRoomAns
  {
    public EnterChatRoomAns() {}
    
    private MSG.ErrorCode _err;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public MSG.ErrorCode err
    {
      get { return _err; }
      set { _err = value; }
    }
  }
  
  [global::ProtoBuf.ProtoContract]
  public partial class EnterChatRoomNot
  {
    public EnterChatRoomNot() {}
    
    private ulong _uid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong uid
    {
      get { return _uid; }
      set { _uid = value; }
    }
    private string _name;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
  }
  
  [global::ProtoBuf.ProtoContract]
  public partial class LeaveChatRoomReq
  {
    public LeaveChatRoomReq() {}
    
    private ulong _rid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong rid
    {
      get { return _rid; }
      set { _rid = value; }
    }
    private string _rkey;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string rkey
    {
      get { return _rkey; }
      set { _rkey = value; }
    }
  }
  
  [global::ProtoBuf.ProtoContract]
  public partial class LeaveChatRoomAns
  {
    public LeaveChatRoomAns() {}
    
    private MSG.ErrorCode _err;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public MSG.ErrorCode err
    {
      get { return _err; }
      set { _err = value; }
    }
  }
  
  [global::ProtoBuf.ProtoContract]
  public partial class LeaveChatRoomNot
  {
    public LeaveChatRoomNot() {}
    
    private ulong _uid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong uid
    {
      get { return _uid; }
      set { _uid = value; }
    }
    private string _name;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
  }
  
}