//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: login.proto
// Note: requires additional types generated from: common.proto
namespace MSG
{
  [global::ProtoBuf.ProtoContract]
  public partial class PingReq
  {
    public PingReq() {}
    
    private string _sessionKey;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string sessionKey
    {
      get { return _sessionKey; }
      set { _sessionKey = value; }
    }
  }
  
  [global::ProtoBuf.ProtoContract]
  public partial class PongAns
  {
    public PongAns() {}
    
    private MSG.ErrorCode _err;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public MSG.ErrorCode err
    {
      get { return _err; }
      set { _err = value; }
    }
  }
  
  [global::ProtoBuf.ProtoContract]
  public partial class LoginReq
  {
    public LoginReq() {}
    
    private string _name;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
  }
  
  [global::ProtoBuf.ProtoContract]
  public partial class LoginAns
  {
    public LoginAns() {}
    
    private MSG.ErrorCode _err;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public MSG.ErrorCode err
    {
      get { return _err; }
      set { _err = value; }
    }

    private string _sessionKey = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string sessionKey
    {
      get { return _sessionKey; }
      set { _sessionKey = value; }
    }

    private MSG.UserData_ _data = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public MSG.UserData_ data
    {
      get { return _data; }
      set { _data = value; }
    }
  }
  
  [global::ProtoBuf.ProtoContract]
  public partial class RegistReq
  {
    public RegistReq() {}
    
    private MSG.UserData_ _data;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, DataFormat = global::ProtoBuf.DataFormat.Default)]
    public MSG.UserData_ data
    {
      get { return _data; }
      set { _data = value; }
    }
  }
  
  [global::ProtoBuf.ProtoContract]
  public partial class RegistAns
  {
    public RegistAns() {}
    
    private MSG.ErrorCode _err;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public MSG.ErrorCode err
    {
      get { return _err; }
      set { _err = value; }
    }
  }
  
  [global::ProtoBuf.ProtoContract]
  public partial class VersionReq
  {
    public VersionReq() {}
    
    private string _version;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string version
    {
      get { return _version; }
      set { _version = value; }
    }
  }
  
  [global::ProtoBuf.ProtoContract]
  public partial class VersionAns
  {
    public VersionAns() {}
    
    private MSG.ErrorCode _err;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public MSG.ErrorCode err
    {
      get { return _err; }
      set { _err = value; }
    }
    private readonly global::System.Collections.Generic.List<MSG.Contents_> _contents = new global::System.Collections.Generic.List<MSG.Contents_>();
    [global::ProtoBuf.ProtoMember(2, DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<MSG.Contents_> contents
    {
      get { return _contents; }
    }
  
  }
  
}