//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: SimTable.proto
namespace MSG
{
  [global::ProtoBuf.ProtoContract]
  public partial class Char
  {
    public Char() {}
    
    private string _TableName;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string TableName
    {
      get { return _TableName; }
      set { _TableName = value; }
    }
    private readonly global::System.Collections.Generic.List<MSG.Char.CharacterTable> _Data = new global::System.Collections.Generic.List<MSG.Char.CharacterTable>();
    [global::ProtoBuf.ProtoMember(2, DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<MSG.Char.CharacterTable> Data
    {
      get { return _Data; }
    }
  
  [global::ProtoBuf.ProtoContract]
  public partial class CharacterTable
  {
    public CharacterTable() {}
    
    private uint _No;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint No
    {
      get { return _No; }
      set { _No = value; }
    }
    private string _Name;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Name
    {
      get { return _Name; }
      set { _Name = value; }
    }
    private uint _AttackRange;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint AttackRange
    {
      get { return _AttackRange; }
      set { _AttackRange = value; }
    }
  }
  
  }
  
  [global::ProtoBuf.ProtoContract]
  public partial class Product
  {
    public Product() {}
    
    private string _TableName;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string TableName
    {
      get { return _TableName; }
      set { _TableName = value; }
    }
    private readonly global::System.Collections.Generic.List<MSG.Product.ProductTable> _Data = new global::System.Collections.Generic.List<MSG.Product.ProductTable>();
    [global::ProtoBuf.ProtoMember(2, DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<MSG.Product.ProductTable> Data
    {
      get { return _Data; }
    }
  
  [global::ProtoBuf.ProtoContract]
  public partial class ProductTable
  {
    public ProductTable() {}
    
    private uint _No;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint No
    {
      get { return _No; }
      set { _No = value; }
    }
    private string _ProductCode;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string ProductCode
    {
      get { return _ProductCode; }
      set { _ProductCode = value; }
    }
    private uint _CharNo;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint CharNo
    {
      get { return _CharNo; }
      set { _CharNo = value; }
    }
    private string _VCType;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string VCType
    {
      get { return _VCType; }
      set { _VCType = value; }
    }
    private uint _Value;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint Value
    {
      get { return _Value; }
      set { _Value = value; }
    }
  }
  
  }
  
  [global::ProtoBuf.ProtoContract]
  public partial class WarriorStat
  {
    public WarriorStat() {}
    
    private string _TableName;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string TableName
    {
      get { return _TableName; }
      set { _TableName = value; }
    }
    private readonly global::System.Collections.Generic.List<MSG.WarriorStat.WarriorStatTable> _Data = new global::System.Collections.Generic.List<MSG.WarriorStat.WarriorStatTable>();
    [global::ProtoBuf.ProtoMember(2, DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<MSG.WarriorStat.WarriorStatTable> Data
    {
      get { return _Data; }
    }
  
  [global::ProtoBuf.ProtoContract]
  public partial class WarriorStatTable
  {
    public WarriorStatTable() {}
    
    private uint _Level;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint Level
    {
      get { return _Level; }
      set { _Level = value; }
    }
    private uint _Exp;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint Exp
    {
      get { return _Exp; }
      set { _Exp = value; }
    }
    private uint _Atk;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint Atk
    {
      get { return _Atk; }
      set { _Atk = value; }
    }
    private uint _Def;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint Def
    {
      get { return _Def; }
      set { _Def = value; }
    }
    private uint _Hp;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint Hp
    {
      get { return _Hp; }
      set { _Hp = value; }
    }
  }
  
  }
  
  [global::ProtoBuf.ProtoContract]
  public partial class ArcherStat
  {
    public ArcherStat() {}
    
    private string _TableName;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string TableName
    {
      get { return _TableName; }
      set { _TableName = value; }
    }
    private readonly global::System.Collections.Generic.List<MSG.ArcherStat.ArcherStatTable> _Data = new global::System.Collections.Generic.List<MSG.ArcherStat.ArcherStatTable>();
    [global::ProtoBuf.ProtoMember(2, DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<MSG.ArcherStat.ArcherStatTable> Data
    {
      get { return _Data; }
    }
  
  [global::ProtoBuf.ProtoContract]
  public partial class ArcherStatTable
  {
    public ArcherStatTable() {}
    
    private uint _Level;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint Level
    {
      get { return _Level; }
      set { _Level = value; }
    }
    private uint _Exp;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint Exp
    {
      get { return _Exp; }
      set { _Exp = value; }
    }
    private uint _Atk;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint Atk
    {
      get { return _Atk; }
      set { _Atk = value; }
    }
    private uint _Def;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint Def
    {
      get { return _Def; }
      set { _Def = value; }
    }
    private uint _Hp;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint Hp
    {
      get { return _Hp; }
      set { _Hp = value; }
    }
  }
  
  }
  
  [global::ProtoBuf.ProtoContract]
  public partial class CharTier
  {
    public CharTier() {}
    
    private string _TableName;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string TableName
    {
      get { return _TableName; }
      set { _TableName = value; }
    }
    private readonly global::System.Collections.Generic.List<MSG.CharTier.CharTierTable> _Data = new global::System.Collections.Generic.List<MSG.CharTier.CharTierTable>();
    [global::ProtoBuf.ProtoMember(2, DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<MSG.CharTier.CharTierTable> Data
    {
      get { return _Data; }
    }
  
  [global::ProtoBuf.ProtoContract]
  public partial class CharTierTable
  {
    public CharTierTable() {}
    
    private uint _Tier;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint Tier
    {
      get { return _Tier; }
      set { _Tier = value; }
    }
    private string _Buff1Type;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Buff1Type
    {
      get { return _Buff1Type; }
      set { _Buff1Type = value; }
    }
    private string _Buff1Value;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Buff1Value
    {
      get { return _Buff1Value; }
      set { _Buff1Value = value; }
    }
    private string _Buff2Type;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Buff2Type
    {
      get { return _Buff2Type; }
      set { _Buff2Type = value; }
    }
    private string _Buff2Value;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Buff2Value
    {
      get { return _Buff2Value; }
      set { _Buff2Value = value; }
    }
    private string _Buff3Type;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Buff3Type
    {
      get { return _Buff3Type; }
      set { _Buff3Type = value; }
    }
    private string _Buff3Value;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Buff3Value
    {
      get { return _Buff3Value; }
      set { _Buff3Value = value; }
    }
  }
  
  }
  
  [global::ProtoBuf.ProtoContract]
  public partial class DungeonTier
  {
    public DungeonTier() {}
    
    private string _TableName;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string TableName
    {
      get { return _TableName; }
      set { _TableName = value; }
    }
    private readonly global::System.Collections.Generic.List<MSG.DungeonTier.DungeonTierTable> _Data = new global::System.Collections.Generic.List<MSG.DungeonTier.DungeonTierTable>();
    [global::ProtoBuf.ProtoMember(2, DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<MSG.DungeonTier.DungeonTierTable> Data
    {
      get { return _Data; }
    }
  
  [global::ProtoBuf.ProtoContract]
  public partial class DungeonTierTable
  {
    public DungeonTierTable() {}
    
    private uint _Tier;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint Tier
    {
      get { return _Tier; }
      set { _Tier = value; }
    }
    private string _Buff1Type;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Buff1Type
    {
      get { return _Buff1Type; }
      set { _Buff1Type = value; }
    }
    private string _Buff1Value;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Buff1Value
    {
      get { return _Buff1Value; }
      set { _Buff1Value = value; }
    }
    private string _Buff2Type;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Buff2Type
    {
      get { return _Buff2Type; }
      set { _Buff2Type = value; }
    }
    private string _Buff2Value;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Buff2Value
    {
      get { return _Buff2Value; }
      set { _Buff2Value = value; }
    }
    private string _Buff3Type;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Buff3Type
    {
      get { return _Buff3Type; }
      set { _Buff3Type = value; }
    }
    private string _Buff3Value;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Buff3Value
    {
      get { return _Buff3Value; }
      set { _Buff3Value = value; }
    }
  }
  
  }
  
  [global::ProtoBuf.ProtoContract]
  public partial class MobAStat
  {
    public MobAStat() {}
    
    private string _TableName;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string TableName
    {
      get { return _TableName; }
      set { _TableName = value; }
    }
    private readonly global::System.Collections.Generic.List<MSG.MobAStat.MobAStatTable> _Data = new global::System.Collections.Generic.List<MSG.MobAStat.MobAStatTable>();
    [global::ProtoBuf.ProtoMember(2, DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<MSG.MobAStat.MobAStatTable> Data
    {
      get { return _Data; }
    }
  
  [global::ProtoBuf.ProtoContract]
  public partial class MobAStatTable
  {
    public MobAStatTable() {}
    
    private uint _Level;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint Level
    {
      get { return _Level; }
      set { _Level = value; }
    }
    private uint _Exp;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint Exp
    {
      get { return _Exp; }
      set { _Exp = value; }
    }
    private uint _Atk;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint Atk
    {
      get { return _Atk; }
      set { _Atk = value; }
    }
    private uint _Def;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint Def
    {
      get { return _Def; }
      set { _Def = value; }
    }
    private uint _Hp;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint Hp
    {
      get { return _Hp; }
      set { _Hp = value; }
    }
  }
  
  }
  
  [global::ProtoBuf.ProtoContract]
  public partial class MobBStat
  {
    public MobBStat() {}
    
    private string _TableName;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string TableName
    {
      get { return _TableName; }
      set { _TableName = value; }
    }
    private readonly global::System.Collections.Generic.List<MSG.MobBStat.MobBStatTable> _Data = new global::System.Collections.Generic.List<MSG.MobBStat.MobBStatTable>();
    [global::ProtoBuf.ProtoMember(2, DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<MSG.MobBStat.MobBStatTable> Data
    {
      get { return _Data; }
    }
  
  [global::ProtoBuf.ProtoContract]
  public partial class MobBStatTable
  {
    public MobBStatTable() {}
    
    private uint _Level;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint Level
    {
      get { return _Level; }
      set { _Level = value; }
    }
    private uint _Exp;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint Exp
    {
      get { return _Exp; }
      set { _Exp = value; }
    }
    private uint _Atk;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint Atk
    {
      get { return _Atk; }
      set { _Atk = value; }
    }
    private uint _Def;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint Def
    {
      get { return _Def; }
      set { _Def = value; }
    }
    private uint _Hp;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint Hp
    {
      get { return _Hp; }
      set { _Hp = value; }
    }
  }
  
  }
  
  [global::ProtoBuf.ProtoContract]
  public partial class MobCStat
  {
    public MobCStat() {}
    
    private string _TableName;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string TableName
    {
      get { return _TableName; }
      set { _TableName = value; }
    }
    private readonly global::System.Collections.Generic.List<MSG.MobCStat.MobCStatTable> _Data = new global::System.Collections.Generic.List<MSG.MobCStat.MobCStatTable>();
    [global::ProtoBuf.ProtoMember(2, DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<MSG.MobCStat.MobCStatTable> Data
    {
      get { return _Data; }
    }
  
  [global::ProtoBuf.ProtoContract]
  public partial class MobCStatTable
  {
    public MobCStatTable() {}
    
    private uint _Level;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint Level
    {
      get { return _Level; }
      set { _Level = value; }
    }
    private uint _Exp;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint Exp
    {
      get { return _Exp; }
      set { _Exp = value; }
    }
    private uint _Atk;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint Atk
    {
      get { return _Atk; }
      set { _Atk = value; }
    }
    private uint _Def;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint Def
    {
      get { return _Def; }
      set { _Def = value; }
    }
    private uint _Hp;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint Hp
    {
      get { return _Hp; }
      set { _Hp = value; }
    }
  }
  
  }
  
  [global::ProtoBuf.ProtoContract]
  public partial class Dungeon
  {
    public Dungeon() {}
    
    private string _TableName;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string TableName
    {
      get { return _TableName; }
      set { _TableName = value; }
    }
    private readonly global::System.Collections.Generic.List<MSG.Dungeon.DungeonTable> _Data = new global::System.Collections.Generic.List<MSG.Dungeon.DungeonTable>();
    [global::ProtoBuf.ProtoMember(2, DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<MSG.Dungeon.DungeonTable> Data
    {
      get { return _Data; }
    }
  
  [global::ProtoBuf.ProtoContract]
  public partial class DungeonTable
  {
    public DungeonTable() {}
    
    private uint _No;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint No
    {
      get { return _No; }
      set { _No = value; }
    }
    private string _Name;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Name
    {
      get { return _Name; }
      set { _Name = value; }
    }
    private uint _Level;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint Level
    {
      get { return _Level; }
      set { _Level = value; }
    }
    private uint _Reward;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint Reward
    {
      get { return _Reward; }
      set { _Reward = value; }
    }
    private uint _MobALv;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint MobALv
    {
      get { return _MobALv; }
      set { _MobALv = value; }
    }
    private uint _MobBLv;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint MobBLv
    {
      get { return _MobBLv; }
      set { _MobBLv = value; }
    }
    private uint _MobCLv;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint MobCLv
    {
      get { return _MobCLv; }
      set { _MobCLv = value; }
    }
  }
  
  }
  
  [global::ProtoBuf.ProtoContract]
  public partial class Item
  {
    public Item() {}
    
    private string _TableName;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string TableName
    {
      get { return _TableName; }
      set { _TableName = value; }
    }
    private readonly global::System.Collections.Generic.List<MSG.Item.ItemTable> _Data = new global::System.Collections.Generic.List<MSG.Item.ItemTable>();
    [global::ProtoBuf.ProtoMember(2, DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<MSG.Item.ItemTable> Data
    {
      get { return _Data; }
    }
  
  [global::ProtoBuf.ProtoContract]
  public partial class ItemTable
  {
    public ItemTable() {}
    
    private uint _No;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint No
    {
      get { return _No; }
      set { _No = value; }
    }
    private string _Name;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Name
    {
      get { return _Name; }
      set { _Name = value; }
    }
    private string _Category;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Category
    {
      get { return _Category; }
      set { _Category = value; }
    }
    private uint _CharNo;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint CharNo
    {
      get { return _CharNo; }
      set { _CharNo = value; }
    }
    private string _Stat;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Stat
    {
      get { return _Stat; }
      set { _Stat = value; }
    }
    private uint _Value;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint Value
    {
      get { return _Value; }
      set { _Value = value; }
    }
  }
  
  }
  
}